version: "3"
services:
    database: # * it's define Perona's Database. (MongoDB)
        image: mongo:4.4.6
        container_name: perona_database
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - perona_database:/data/db
    perona: # * it's define Perona's Client. (Rust)
        container_name: perona_client
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        environment:
            - DATABASE_URI=mongodb://localhost:27017/perona_database
            - DATABASE_TEST_URI=mongodb://localhost:27017/perona_database
        env_file:
            - .env.production
volumes:
    perona_database:
        name: perona_database
