name: Continuous Integration

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}

        env:
            DATABASE_TEST_URI: ${{ secrets.DATABASE_TEST_URI }}

        steps:
            - uses: actions/checkout@v3

            - name: Testing project
              run: |
                cargo check --verbose
                cargo test --all --verbose

            - name: Building project
              run: |
                cargo check --verbose
                cargo build --verbose
