name: CI

on: [push, pull_request]

env:
    APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    DATABASE_URI: ${{ secrets.DATABASE_URI }}
    DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - name: Building project
              run: cargo build --verbose




