name: CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Build and Test repository
              run: |
                cargo build --verbose
                cargo test --verbose




